/*----------------------------------------------------------
MASV - HO TEN CAC THANH VIEN NHOM:

20120117-Phạm Nguyễn Khánh Minh 
20120389-Nguyễn Thị Bích Trâm
20120576-Nguyễn Bửu Thạch
20120595-Phạm Minh Tiến 

LAB: 04 - NHOM 10
NGAY:25/04/2023
----------------------------------------------------------*/

USE master 
CREATE 
--DROP
DATABASE QLSVNhomLab4
GO 
USE QLSVNhomLab4
GO

--DROP TABLE BANGDIEM
--DROP TABLE HOCPHAN
--DROP TABLE SINHVIEN
--DROP TABLE LOP 
--DROP TABLE NHANVIEN

CREATE TABLE SINHVIEN
(
	MASV VARCHAR(20),
	HOTEN NVARCHAR(100)  NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR (20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL,
	CONSTRAINT PK_SV
	PRIMARY KEY(MASV)
);
GO
CREATE TABLE NHANVIEN
(
	MANV VARCHAR (20),
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR (20),
	LUONG VARBINARY(MAX),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL,
	PUBKEY VARCHAR(MAX),
	CONSTRAINT PK_NV
	PRIMARY KEY(MANV)
);
GO
CREATE TABLE LOP
(
	MALOP VARCHAR (20),
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR (20),
	CONSTRAINT PK_L
	PRIMARY KEY(MALOP)
);
GO
CREATE TABLE HOCPHAN
(
	MAHP VARCHAR (20),
	TENHP NVARCHAR(100) NOT NULL,
	SOTC INT,
	CONSTRAINT PK_HP
	PRIMARY KEY(MAHP)
);
GO
CREATE  TABLE BANGDIEM
(
	MASV VARCHAR (20),
	MAHP VARCHAR (20),
	DIEMTHI VARBINARY(MAX),
	CONSTRAINT PK_BD
	PRIMARY KEY(MASV, MAHP)
);
GO
ALTER TABLE SINHVIEN
ADD 
CONSTRAINT FK_SV_L
FOREIGN KEY(MALOP)
REFERENCES LOP
ON DELETE CASCADE
ON UPDATE CASCADE;
GO
ALTER TABLE LOP
ADD 
CONSTRAINT FK_L_NV
FOREIGN KEY(MANV)
REFERENCES NHANVIEN
ON DELETE CASCADE
ON UPDATE CASCADE;
GO
ALTER TABLE BANGDIEM
ADD 
CONSTRAINT FK_BD_SV
FOREIGN KEY(MASV)
REFERENCES SINHVIEN,
CONSTRAINT FK_BD_HP
FOREIGN KEY(MAHP)
REFERENCES HOCPHAN
ON DELETE CASCADE
ON UPDATE CASCADE;
GO
ALTER TABLE NHANVIEN ADD CONSTRAINT UQ_TENDN UNIQUE (TENDN);
ALTER TABLE SINHVIEN ADD CONSTRAINT UK_TENDN UNIQUE(TENDN);
GO
--i.
create proc SP_INS_PUBLIC_ENCRYPT_NHANVIEN 
(
	@MANV varchar(20),
	@HOTEN nvarchar(100),
	@EMAIL varchar(20),
	@LUONG varbinary(max),
	@TENDN nvarchar(100),
	@MATKHAU varbinary(max),
	@PUB varchar(max)
)
As
	IF NOT EXISTS (SELECT * FROM SINHVIEN WHERE TENDN = @TENDN)
	Begin
		insert into NHANVIEN(MANV,HOTEN,EMAIL,LUONG,TENDN,MATKHAU,PUBKEY)
		values (@MANV, @HOTEN, @EMAIL,@LUONG, @TENDN, @MATKHAU,@PUB);
	END
	ELSE
    BEGIN
        THROW 50001, 'TENDN already exists in SINHVIEN.', 1;
    END
GO

--ii.
CREATE PROCEDURE SP_SEL_PUBLIC_ENCRYPT_NHANVIEN
	@TENDN NVARCHAR(100),
	@MK VARBINARY(max)
AS
	SELECT MANV, HOTEN, EMAIL, LUONG
	FROM NHANVIEN
	WHERE TENDN = @TENDN AND MATKHAU = @MK
GO
create procedure SP_SEL_ENCRYPT_NHANVIEN
As
	Begin		
		SELECT * FROM NHANVIEN 		
	END
GO
--SP Update nhan vien
create 
--drop
procedure SP_UPD_NHANVIEN
(
	@MANV varchar(20),
	@HOTEN nvarchar(100),
	@EMAIL varchar(20),
	@LUONG varbinary(max),
	@TENDN nvarchar(100),
	@MATKHAU varbinary(max),
	@PUB varchar(max)
)
As
	IF NOT EXISTS (SELECT * FROM SINHVIEN WHERE TENDN = @TENDN)
	Begin
		UPDATE NHANVIEN
		SET		
			HOTEN = @HOTEN,
			EMAIL = @EMAIL,
			LUONG = @LUONG,
			TENDN = @TENDN,
			MATKHAU = @MATKHAU,
			PUBKEY = @PUB
		WHERE
			MANV = @MANV 
	END
	ELSE
    BEGIN
        THROW 50001, 'TENDN already exists in SINHVIEN.', 1;
    END
GO

--SP Xóa nhân viên
create procedure SP_DEL_NHANVIEN
(
	@MANV varchar(20)
)
As
	Begin
		DELETE FROM NHANVIEN WHERE MANV = @MANV
	END
GO

--SP cho màn hình đăng nhập
create 
--drop 
proc SP_LOGIN
(
	@TENDN nvarchar(100),
	@MATKHAU varbinary(max)
)
As
	Begin
		SELECT * FROM NHANVIEN WHERE MANV = @TENDN and MATKHAU = @MATKHAU
	END
GO

--NHANVIEN
EXEC SP_INS_PUBLIC_ENCRYPT_NHANVIEN  'NV01', N'NGUYEN VAN A', 'nva@yahoo.com', null, N'NVA', 0x7C4A8D09CA3762AF61E59520943DC26494F8941B,
'BgIAAACkAABSU0ExAAgAAAEAAQAZbzAqPdataDLwrllN2vaHcCA54iHe80VqE8pPZe+Y1mNgIZEaVLptGGlsAS6DUqLKiXVdDzraOm+jXLi/jl8wHUqVkOsNesjPYYBtwrYKLQRkq
TNAWrGI6ovvzCvtmi0cleCDZbJ44SVkmkgZHJ2AWHAofpZAvro+dLNlZIhwAYco81tFBbHpbPMtPP6iGwyKrt5EH/ydZZ/l9rlYmfPN/BJpspuotqmO2ps5iqgbeSTU9Eoe845cbKDbq
Oorv0C75uS53AO7H0e9kQkZuuLb+VzY7CosVk2c5fd4FsLnyN4Hu+pX4xTJIelCi9G5dVh1qUIsDgjMbEFNJOhgP3k'
EXEC SP_INS_PUBLIC_ENCRYPT_NHANVIEN  'NV02', N'NGUYEN VAN B', 'nvb@yahoo.com', null, N'NVB', 0x7C4A8D09CA3762AF61E59520943DC26494F8941B,null
GO
---Username: NVA, Password = '123456'
--NHANVIEN
EXEC SP_SEL_ENCRYPT_NHANVIEN
exec SP_DEL_NHANVIEN 'NV01'
--thêm lớp
create proc SP_INS_LOP
(
	@MALOP VARCHAR (20),
	@TENLOP NVARCHAR(100),
	@MANV VARCHAR (20)
)
As
	Begin
		insert into LOP(MALOP,TENLOP,MANV)
		values (@MALOP, @TENLOP, @MANV)
	end
GO
--xem lớp 
CREATE 
--drop
PROCEDURE SP_SEL_LOP
    @TUKHOA NVARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT * FROM LOP 
    WHERE MALOP LIKE '%' + @TUKHOA + '%' 
    OR TENLOP LIKE N'%' + @TUKHOA + '%' 
    OR MANV LIKE '%' + @TUKHOA + '%';
END
go
--sửa lớp
create 
--drop
procedure SP_UPD_LOP
(
	@MALOP VARCHAR (20),
	@TENLOP NVARCHAR(100),
	@MANV VARCHAR (20)
)
As
	Begin
		UPDATE LOP
		SET		
			TENLOP = @TENLOP,
			MANV = @MANV
		WHERE
			MALOP = @MALOP 
	END
GO
--xóa lớp
create procedure SP_DEL_LOP
(
	@MALOP VARCHAR (20)
)
As
	Begin
		DELETE FROM LOP WHERE MALOP = @MALOP 
	END
GO
--SP lấy các sinh viên thuộc một lớp
create 
--drop
proc SP_CL_STU
(
	@MALOP varchar(20),
	@TUKHOA NVARCHAR(100)

)
As
	Begin
		SET NOCOUNT ON;

		select * from SINHVIEN where MALOP = @maLop    
		AND (MASV LIKE '%' + @TUKHOA + '%' 
		OR HOTEN LIKE N'%' + @TUKHOA + '%' 
		OR CONVERT(nvarchar(20), NGAYSINH, 23) LIKE '%' + @TUKHOA + '%'
		OR DIACHI LIKE N'%' + @TUKHOA + '%'
		OR TENDN LIKE N'%' + @TUKHOA + '%')
	End
Go

--SP thêm sinh viên
create proc SP_INS_PUBLIC_ENCRYPT_SINHVIEN
(
	@MASV nvarchar(20),
	@HOTEN nvarchar(100),
	@NGAYSINH datetime,
	@DIACHI nvarchar(200),
	@MALOP varchar(20),
	@TENDN nvarchar(100),
	@MATKHAU varbinary(max)
)
As
	
	IF NOT EXISTS (SELECT * FROM NHANVIEN WHERE TENDN = @TENDN)
	Begin
		INSERT INTO SINHVIEN
		VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, @MATKHAU)
	END
	ELSE
    BEGIN
        THROW 50001, 'TENDN already exists in NHANVIEN.', 1;
    END
GO
--SP Update sinh viên
create --drop 
procedure SP_UPD_SINHVIEN
(
	@MASV nvarchar(20) ,
	@HOTEN nvarchar(100) ,
	@NGAYSINH datetime,
	@DIACHI nvarchar(200),
	@MALOP varchar(20),
	@TENDN nvarchar(100),
	@MATKHAU varbinary(max)
)
As			
	BEGIN			
		UPDATE SINHVIEN
			SET
				HOTEN = @HOTEN,
				NGAYSINH = @NGAYSINH,
				DIACHI = @DIACHI,
				MALOP = @MALOP,
				TENDN = @TENDN,
				MATKHAU = @MATKHAU
			WHERE
				MASV = @MASV				
	END
GO
-- SP xóa sinh viên
create procedure SP_DEL_SINHVIEN
(
	@MASV nvarchar(20)
)
As
	DELETE FROM SINHVIEN WHERE MASV = @MASV
go
exec SP_DEL_SINHVIEN 'SV02'

--SP Update bảng điểm
CREATE PROCEDURE SP_UPDATE_HOCPHAN_BANGDIEM
    @MAHP VARCHAR(20),
    @TENHP NVARCHAR(100),
    @SOTC INT,
    @MASV VARCHAR(20),
    @DIEMTHI VARBINARY(MAX)
AS
BEGIN
    -- Cập nhật dữ liệu trong bảng HOCPHAN
    UPDATE HOCPHAN
    SET TENHP = @TENHP, SOTC = @SOTC
    WHERE MAHP = @MAHP

    -- Cập nhật dữ liệu trong bảng BANGDIEM
    UPDATE BANGDIEM
    SET DIEMTHI = @DIEMTHI
    WHERE MASV = @MASV AND MAHP = @MAHP
END
GO

--them hoc phan bảng điểm 
CREATE PROCEDURE SP_INSERT_HOCPHAN_BANGDIEM
	@MAHP VARCHAR(20),
	@TENHP NVARCHAR(100),
	@SOTC INT,
	@MASV VARCHAR(20),
	@DIEMTHI VARBINARY(MAX)
AS
	BEGIN
		-- Chèn dữ liệu vào bảng HOCPHAN
		INSERT INTO HOCPHAN (MAHP, TENHP, SOTC)
		VALUES (@MAHP, @TENHP, @SOTC)
		-- Chèn dữ liệu vào bảng BANGDIEM
		INSERT INTO BANGDIEM (MASV, MAHP, DIEMTHI)
		VALUES (@MASV, @MAHP, @DIEMTHI)
	END
GO
select * from BANGDIEM

--SP để người quản lý lấy public key của mình và bảng điểm cụ thể của nhân viên của một sinh viên mà mình quản lý
create
--drop
procedure SP_SEL_BANGDIEM
(
	@MANV varchar(20),
	@MASV nvarchar(20),
	@TUKHOA NVARCHAR(100)
)
As
	BEGIN
		SET NOCOUNT ON;
		SELECT BANGDIEM.MAHP,TENHP,HOCPHAN.SOTC, DIEMTHI, NHANVIEN.PUBKEY FROM BANGDIEM 
		inner join SINHVIEN on BANGDIEM.MASV = SINHVIEN.MASV
		inner join LOP on SINHVIEN.MALOP = LOP.MALOP 
		inner join NHANVIEN on LOP.MANV = NHANVIEN.MANV 
		inner join HOCPHAN on BANGDIEM.MAHP = HOCPHAN.MAHP 
		WHERE BANGDIEM.MASV = @MASV AND LOP.MANV = @MANV
			AND (BANGDIEM.MAHP LIKE '%' + @TUKHOA + '%' 
			OR TENHP LIKE N'%' + @TUKHOA + '%' 
			OR HOCPHAN.SOTC LIKE '%' + @TUKHOA + '%')	
	END
GO

CREATE PROCEDURE SP_DELETE_HOCPHAN_BANGDIEM
@MAHP VARCHAR(20),
@MASV VARCHAR(20)
AS
BEGIN
	-- Xóa dữ liệu trong bảng BANGDIEM
	DELETE FROM BANGDIEM
	WHERE MAHP = @MAHP AND MASV = @MASV
	-- Xóa dữ liệu trong bảng HOCPHAN
	DELETE FROM HOCPHAN
	WHERE MAHP = @MAHP
END